### ISSUE TITLE
🛠️ compose 없이 container 단위로 구성

### ISSUE THREAD

**Issue by YubinMoon** [DevTrack6/Scheduler#1]
CI/CD의 용이성과 개발 편의성을 위해 docker compose에서 분리하여 각각 컨테이너 별로 관리하려 합니다.
과정에서 nginx는 제거하고 DB는 prod 버전은 prod 서버에 컨테이너로 따로 열어두고 local 버전은 각자 컨테이너를 띄워서 연결 할 계획입니다.

**Comment by YubinMoon** [comment]
여기에 의견 부탁드릴게요

**Comment by hjklo0220** [comment]
좋은 의견입니다. app은 일단 local, prod만 구성하고 어느정도 완성되고 나중에 stage구성하는것은 어떨까요?
이번주에 jenkins CI(lint check - image build) / CD(image push - pull - run) 정도 구성해놓고 다음주부터 백엔드 개발 차근차근 시작해보는것은 어떨까요?
